// R10 — weekly sales digest ("scheduled report" mail, round-9 backlog item b).
// R11 — monthly variant (round-10 backlog item b): the same report for a
// 30-day window, with an INDEPENDENT freshness guard.
//
// The store owner gets a sales summary through the SAME MailMessage outbox
// every transactional mail uses (kind SALES_DIGEST). Scheduling needs no
// external cron: healthz housekeeping calls queueSalesDigestIfDue() on its
// 6-hourly sweep and the per-window freshness guards below make each window
// fire exactly once per its period. A manual OWNER/admin trigger exists at
// POST /api/admin/reports/digest (?force=1 bypasses the guard, ?days=30
// selects the monthly window).
//
// The digest is PLAIN TEXT (same no-HTML-injection surface as order mails);
// money uses the shared formatMinor; deltas compare the window against the
// equally-sized window before it.
//
// Window identification: MailMessage rows carry no window column, so the
// subjects generated by THIS module double as markers — the EN subject always
// contains 'weekly digest' or 'monthly digest' and the FA subject always
// contains 'هفتگی' or 'ماهانه'. The guard/status queries below match on
// those markers (disjoint on purpose — do not reword the subjects).
import { db } from '@/lib/db'
import type { Prisma } from '@prisma/client'
import { siteUrlFrom } from '@/lib/site'
import { formatMinor } from '@/lib/server/money'
import { pickLocale } from '@/lib/server/utils'

export interface DigestResult {
  queued: boolean
  skipped?: 'recent' | 'no-recipient'
  to?: string
  subject?: string
  days?: number
}

export const DIGEST_WINDOWS = [7, 30] as const
export type DigestWindowDays = (typeof DIGEST_WINDOWS)[number]

const DIGEST_WINDOW_DAYS = 7
/** A digest this fresh suppresses the automatic one (manual force bypasses). */
const DIGEST_FRESH_MS = DIGEST_WINDOW_DAYS * 24 * 3600 * 1000

/** Subject markers used to tell the two windows apart in the outbox — see the
 *  module header. Keep these EXACTLY in sync with the subject builders. */
function windowMarker(days: number): string[] {
  return days === 30 ? ['monthly digest', 'ماهانه'] : ['weekly digest', 'هفتگی']
}

function whereWindow(days: number): { subject: { contains: string } }[] {
  return windowMarker(days).map((m) => ({ subject: { contains: m } }))
}

/** Persian digits for the FA body (server-side — lib/format is client-only). */
function toFa(s: string | number): string {
  return String(s).replace(/\d/g, (d) => '۰۱۲۳۴۵۶۷۸۹'[Number(d)])
}

function fmtRange(from: Date, to: Date, locale: string): string {
  try {
    const loc = locale === 'fa' ? 'fa-IR' : 'en-GB'
    const opts: Intl.DateTimeFormatOptions = { day: 'numeric', month: 'short' }
    const f = new Intl.DateTimeFormat(loc, opts)
    return `${f.format(from)} – ${f.format(to)}`
  } catch {
    return `${from.toISOString().slice(0, 10)} – ${to.toISOString().slice(0, 10)}`
  }
}

/** "+12%" | "−5%" | "— change" (previous window was empty). */
function delta(cur: number, prev: number, fa: boolean): string {
  if (prev <= 0) return fa ? 'هفتهٔ اول' : 'first week'
  const pct = Math.round(((cur - prev) / prev) * 100)
  if (pct === 0) return fa ? 'بدون تغییر' : 'no change'
  const sign = pct > 0 ? '+' : '−'
  return fa ? `${sign}${toFa(Math.abs(pct))}٪` : `${sign}${Math.abs(pct)}%`
}

/** Recipient: the store support email from settings, else the OWNER's login. */
async function resolveRecipient(): Promise<{ email: string; locale: string } | null> {
  const store = await db.settings.findUnique({ where: { key: 'store' } }).catch(() => null)
  const parsed = store?.valueJson ? (JSON.parse(store.valueJson) as { email?: string }).email : undefined
  if (parsed?.trim()) return { email: parsed.trim(), locale: 'en' }
  const owner = await db.user.findFirst({
    where: { role: 'OWNER' },
    orderBy: { createdAt: 'asc' },
    select: { email: true, preferredLocale: true },
  })
  return owner ? { email: owner.email, locale: owner.preferredLocale === 'fa' ? 'fa' : 'en' } : null
}

export interface DigestData {
  paidOrders: { cur: number; prev: number }
  revenueMinor: { cur: number; prev: number }
  refundsMinor: number
  aovMinor: number
  topProducts: { title: string; units: number }[]
  topCountries: { code: string; orders: number; revenueMinor: number }[]
  lowStock: { title: string; sku: string; stock: number }[]
  pendingReviews: number
  openTickets: number
}

/** Collect the digest numbers. Exported for tests/manual preview. */
export async function collectDigestData(now = new Date(), days: number = DIGEST_WINDOW_DAYS): Promise<DigestData> {
  const curStart = new Date(now.getTime() - days * 86400000)
  const prevStart = new Date(now.getTime() - 2 * days * 86400000)
  const paid: Prisma.OrderWhereInput = { paymentStatus: { in: ['SUCCEEDED', 'PARTIALLY_REFUNDED'] } }

  const [curOrders, prevOrders, curAgg, prevAgg, refunds, curItems, lowStockVariants, pendingReviews, openTickets] =
    await Promise.all([
      db.order.count({ where: { ...paid, createdAt: { gte: curStart } } }),
      db.order.count({ where: { ...paid, createdAt: { gte: prevStart, lt: curStart } } }),
      db.order.aggregate({ where: { ...paid, createdAt: { gte: curStart } }, _sum: { totalMinor: true } }),
      db.order.aggregate({ where: { ...paid, createdAt: { gte: prevStart, lt: curStart } }, _sum: { totalMinor: true } }),
      db.refund.aggregate({
        where: { status: 'SUCCEEDED', createdAt: { gte: curStart } },
        _sum: { amountMinor: true },
      }),
      db.orderItem.findMany({
        where: { order: { ...paid, createdAt: { gte: curStart } } },
        include: { variant: { include: { product: { include: { translations: true } } } } },
      }),
      db.variant
        .findMany({
          where: { isActive: true, stock: { lte: 5 } },
          include: { product: { include: { translations: true } } },
          orderBy: { stock: 'asc' },
          take: 24,
        })
        .then((rows) => rows.filter((v) => v.stock <= v.lowStockThreshold).slice(0, 6)),
      db.review.count({ where: { moderationState: 'PENDING' } }),
      db.ticket.count({ where: { status: { in: ['OPEN', 'AWAITING_SUPPORT'] } } }),
    ])

  // Per-product units (grouped in JS — SQLite has no relational groupBy here).
  const byProduct = new Map<string, { title: string; units: number }>()
  for (const it of curItems) {
    const title =
      it.variant?.product
        ? (pickLocale(it.variant.product.translations, 'en')?.title ?? it.variant.product.slug)
        : it.titleEn
    const e = byProduct.get(title) ?? { title, units: 0 }
    e.units += it.quantity
    byProduct.set(title, e)
  }

  // Per-country from the shipping snapshot.
  const byCountry = new Map<string, { code: string; orders: number; revenueMinor: number }>()
  const curOrdersRows = await db.order.findMany({
    where: { ...paid, createdAt: { gte: curStart } },
    select: { shippingAddressJson: true, totalMinor: true },
  })
  for (const o of curOrdersRows) {
    let code = '??'
    try {
      const addr = o.shippingAddressJson ? (JSON.parse(o.shippingAddressJson) as { countryCode?: string }) : null
      code = addr?.countryCode ?? '??'
    } catch {
      // keep placeholder
    }
    const e = byCountry.get(code) ?? { code, orders: 0, revenueMinor: 0 }
    e.orders += 1
    e.revenueMinor += o.totalMinor
    byCountry.set(code, e)
  }

  const revenueCur = curAgg._sum.totalMinor ?? 0
  return {
    paidOrders: { cur: curOrders, prev: prevOrders },
    revenueMinor: { cur: revenueCur, prev: prevAgg._sum.totalMinor ?? 0 },
    refundsMinor: refunds._sum.amountMinor ?? 0,
    aovMinor: curOrders > 0 ? Math.round(revenueCur / curOrders) : 0,
    topProducts: [...byProduct.values()].sort((a, b) => b.units - a.units).slice(0, 5),
    topCountries: [...byCountry.values()].sort((a, b) => b.revenueMinor - a.revenueMinor).slice(0, 4),
    lowStock: lowStockVariants.map((v) => ({
      title: pickLocale(v.product.translations, 'en')?.title ?? v.product.slug,
      sku: v.sku,
      stock: v.stock,
    })),
    pendingReviews,
    openTickets,
  }
}

/** Build the localized plain-text digest body. Exported for preview tests. */
export function buildDigestBody(
  data: DigestData,
  locale: string,
  origin: string,
  now = new Date(),
  days: number = DIGEST_WINDOW_DAYS,
): { fa: boolean; text: string } {
  const fa = locale === 'fa'
  const to = new Date(now)
  const from = new Date(now.getTime() - days * 86400000)
  const range = fmtRange(from, to, locale)
  const dOrders = delta(data.paidOrders.cur, data.paidOrders.prev, fa)
  const dRevenue = delta(data.revenueMinor.cur, data.revenueMinor.prev, fa)
  const n = (x: number | string) => (fa ? toFa(x) : String(x))
  const money = (m: number) => (fa ? toFa(formatMinor(m)) : formatMinor(m))
  const fa_window = days === 30 ? '\u06af\u0632\u0627\u0631\u0634 \u0641\u0631\u0648\u0634 \u06f3\u06f0 \u0631\u0648\u0632 \u06af\u0630\u0634\u062a\u0647' : '\u06af\u0632\u0627\u0631\u0634 \u0641\u0631\u0648\u0634 \u06f7 \u0631\u0648\u0632 \u06af\u0630\u0634\u062a\u0647'
  const fa_prev = days === 30 ? '\u06f3\u06f0 \u0631\u0648\u0632 \u0642\u0628\u0644 \u0627\u0632 \u0622\u0646' : '\u06f7 \u0631\u0648\u0632 \u0642\u0628\u0644 \u0627\u0632 \u0622\u0646'
  const en_window = days === 30 ? 'the last 30 days' : 'the last 7 days'

  const lines: string[] = fa
    ? [
        '\u0633\u0644\u0627\u0645\u060c',
        `${fa_window} (${range}) \u2014 \u0628\u0627 \u0645\u0642\u0627\u06cc\u0633\u0647\u0654 ${fa_prev}:`,
        '',
        `\u2022 \u0633\u0641\u0627\u0631\u0634\u200c\u0647\u0627\u06cc \u067e\u0631\u062f\u0627\u062e\u062a\u200c\u0634\u062f\u0647: ${n(data.paidOrders.cur)} (${dOrders})`,
        `\u2022 \u062f\u0631\u0622\u0645\u062f: ${money(data.revenueMinor.cur)} (${dRevenue})`,
        `\u2022 \u0645\u0631\u062c\u0648\u0639\u06cc\u200c\u0647\u0627: ${money(data.refundsMinor)}`,
        `\u2022 \u0645\u06cc\u0627\u0646\u06af\u06cc\u0646 \u0633\u0641\u0627\u0631\u0634: ${money(data.aovMinor)}`,
      ]
    : [
        'Hello,',
        `Here is how the store did over ${en_window} (${range}), with the previous ${days} days in brackets:`,
        '',
        `\u2022 Paid orders: ${n(data.paidOrders.cur)} (${dOrders})`,
        `\u2022 Revenue: ${money(data.revenueMinor.cur)} (${dRevenue})`,
        `\u2022 Refunds: ${money(data.refundsMinor)}`,
        `\u2022 Average order: ${money(data.aovMinor)}`,
      ]

  if (data.topProducts.length > 0) {
    lines.push('', fa ? (days === 30 ? '\u067e\u0631\u0641\u0631\u0648\u0634\u200c\u062a\u0631\u06cc\u0646\u200c\u0647\u0627\u06cc \u0627\u06cc\u0646 \u0645\u0627\u0647:' : '\u067e\u0631\u0641\u0631\u0648\u0634\u200c\u062a\u0631\u06cc\u0646\u200c\u0647\u0627\u06cc \u0627\u06cc\u0646 \u0647\u0641\u062a\u0647:') : days === 30 ? 'Best sellers this month:' : 'Best sellers this week:')
    data.topProducts.forEach((p, i) => lines.push(`${n(i + 1)}. ${p.title} \u2014 ${n(p.units)} ${fa ? '\u0646\u0633\u062e\u0647' : 'sold'}`))
  }
  if (data.topCountries.length > 0) {
    lines.push('', fa ? '\u0628\u0627\u0632\u0627\u0631\u0647\u0627:' : 'Where orders came from:')
    for (const c of data.topCountries) lines.push(`\u2022 ${c.code} \u2014 ${n(c.orders)} ${fa ? '\u0633\u0641\u0627\u0631\u0634' : 'orders'} \u00b7 ${money(c.revenueMinor)}`)
  }
  if (data.lowStock.length > 0) {
    lines.push('', fa ? '\u0645\u0648\u062c\u0648\u062f\u06cc \u06a9\u0645 (\u0628\u0647\u062a\u0631 \u0627\u0633\u062a \u0634\u0627\u0631\u0698 \u06a9\u0646\u06cc\u062f):' : 'Low stock right now (worth reordering):')
    for (const v of data.lowStock) lines.push(`\u2022 ${v.title} (${v.sku}) \u2014 ${n(v.stock)} ${fa ? '\u0639\u062f\u062f' : 'left'}`)
  }
  if (data.pendingReviews > 0 || data.openTickets > 0) {
    lines.push('', fa ? '\u062f\u0631 \u0627\u0646\u062a\u0638\u0627\u0631 \u0634\u0645\u0627:' : 'Also waiting for you:')
    if (data.pendingReviews > 0) lines.push(`\u2022 ${n(data.pendingReviews)} ${fa ? '\u0646\u0638\u0631 \u062f\u0631 \u0627\u0646\u062a\u0638\u0627\u0631 \u0628\u0631\u0631\u0633\u06cc' : 'review(s) pending moderation'}`)
    if (data.openTickets > 0) lines.push(`\u2022 ${n(data.openTickets)} ${fa ? '\u062a\u06cc\u06a9\u062a \u0628\u06cc\u200c\u067e\u0627\u0633\u062e' : 'open ticket(s) without a reply'}`)
  }

  lines.push(
    '',
    fa ? '\u0645\u062f\u06cc\u0631\u06cc\u062a \u0641\u0631\u0648\u0634\u06af\u0627\u0647:' : 'Manage the store:',
    `${origin}/admin`,
    '',
    fa
      ? (days === 30 ? '\u067e\u0631\u0633\u200c\u067e\u06cc\u06a9\u0633 \u2014 \u06af\u0632\u0627\u0631\u0634 \u062e\u0648\u062f\u06a9\u0627\u0631 \u0645\u0627\u0647\u0627\u0646\u0647' : '\u067e\u0631\u0633\u200c\u067e\u06cc\u06a9\u0633 \u2014 \u06af\u0632\u0627\u0631\u0634 \u062e\u0648\u062f\u06a9\u0627\u0631 \u0647\u0641\u062a\u06af\u06cc')
      : (days === 30 ? 'Persepix \u2014 automatic monthly report' : 'Persepix \u2014 automatic weekly report'),
  )
  return { fa, text: lines.join('\n') }
}

/** Queue one SALES_DIGEST mail for the given window. Idempotent per window:
 *  a digest of the SAME window younger than its own period suppresses the
 *  automatic queueing (force=1 bypasses \u2014 manual sends are always allowed
 *  and restart the guard, since they create the newest row for that window).
 *  The windows are independent: a weekly send never blocks the monthly one. */
export async function queueSalesDigestEmail(
  origin?: string | { headers: Headers } | null,
  opts?: { force?: boolean; days?: DigestWindowDays },
): Promise<DigestResult> {
  const days: DigestWindowDays = opts?.days === 30 ? 30 : 7
  if (!opts?.force) {
    const recent = await db.mailMessage.findFirst({
      where: { kind: 'SALES_DIGEST', OR: whereWindow(days), createdAt: { gte: new Date(Date.now() - days * 86400000) } },
      select: { id: true },
    })
    if (recent) return { queued: false, skipped: 'recent', days }
  }

  const recipient = await resolveRecipient()
  if (!recipient) return { queued: false, skipped: 'no-recipient', days }

  const data = await collectDigestData(new Date(), days)
  const site = typeof origin === 'string' ? origin : siteUrlFrom(origin ?? null)
  const { fa, text } = buildDigestBody(data, recipient.locale, site, new Date(), days)
  const range = fmtRange(new Date(Date.now() - days * 86400000), new Date(), recipient.locale)

  const subject = fa
    ? (days === 30
        ? `\u067e\u0631\u0633\u200c\u067e\u06cc\u06a9\u0633 \u2014 \u06af\u0632\u0627\u0631\u0634 \u0645\u0627\u0647\u0627\u0646\u0647 \u0641\u0631\u0648\u0634 (${range})`
        : `\u067e\u0631\u0633\u200c\u067e\u06cc\u06a9\u0633 \u2014 \u06af\u0632\u0627\u0631\u0634 \u0647\u0641\u062a\u06af\u06cc \u0641\u0631\u0648\u0634 (${range})`)
    : (days === 30 ? `Persepix monthly digest \u2014 ${range}` : `Persepix weekly digest \u2014 ${range}`)
  await db.mailMessage.create({
    data: { to: recipient.email, subject, kind: 'SALES_DIGEST', bodyText: text, locale: fa ? 'fa' : 'en' },
  })
  return { queued: true, to: recipient.email, subject, days }
}

/** Status for one window: newest row of that window + total unsent digests.
 *  Exported for the admin reports panel (GET /api/admin/reports/digest). */
export async function digestWindowStatus(days: DigestWindowDays) {
  const [last, queuedUnsent] = await Promise.all([
    db.mailMessage.findFirst({
      where: { kind: 'SALES_DIGEST', OR: whereWindow(days) },
      orderBy: { createdAt: 'desc' },
      select: { createdAt: true, sentAt: true, to: true },
    }),
    db.mailMessage.count({ where: { kind: 'SALES_DIGEST', sentAt: null } }),
  ])
  return {
    lastDigestAt: last?.createdAt.toISOString() ?? null,
    lastDigestSent: last?.sentAt?.toISOString() ?? null,
    lastTo: last?.to ?? null,
    queuedUnsent,
  }
}

/** healthz housekeeping hook: swallows every error (must never fail the
 *  probe). Both windows get their guarded attempt \u2014 each is a cheap no-op
 *  query unless its own period has elapsed. */
export async function queueSalesDigestIfDue(): Promise<void> {
  await queueSalesDigestEmail(undefined, { days: 7 }).catch(() => undefined)
  await queueSalesDigestEmail(undefined, { days: 30 }).catch(() => undefined)
}
